[package]
name = "cyberlight"
authors = ["Maciej Gierada @mgierada"]
version = "0.14.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
reqwest = {version = "0.12.1", features = ["blocking", "json"]}
serde = {version = "1.0.197", features = ["derive"]}
serde_json = "1.0.114"
lazy_static = "1.4.0"
govee-api = {version = "1.3.5"}
# govee-api = {version = "1.3.0", path = "../../govee-api.git/add_clone_derive_to_PayloadBody/"}

[dependencies.rocket]
version = "0.5.0"
features = ["json"]

[dev-dependencies]
mockito = "1.4.0"
tokio = {version = "1.36.0", features = ["full"]}

[[bin]]
name = "cyberligth"
path = "src/main.rs"

