[package]
name = "rust_that_light"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
reqwest = "0.11.14"
serde = {version = "1.0.154", features = ["derive"]}
serde_json = "1.0.94"
