[package]
name = "rust_that_light"
authors = ["Maciej Gierada @mgierada"]
version = "0.12.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
reqwest = {version = "0.11.22", features = ["blocking", "json"]}
serde = {version = "1.0.190", features = ["derive"]}
serde_json = "1.0.108"
lazy_static = "1.4.0"
govee-api = {version = "1.3.2"}
# govee-api = {version = "1.3.0", path = "../../govee-api.git/add_clone_derive_to_PayloadBody/"}

[dependencies.rocket]
version = "0.5.0-rc.4"
features = ["json"]

[dev-dependencies]
mockito = "1.2.0"
tokio = {version = "1.33.0", features = ["full"]}

[[bin]]
name = "rust_that_light"
path = "src/main.rs"

