# fly.toml app configuration file generated for rust-that-light on 2023-06-01T10:14:54+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rust-that-light"
primary_region = "ams"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
