name: Rust Lint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint Code
        run: |
          cargo fmt --all -- --check
          cargo clippy --all-targets --all-features -- -D warnings
      - name: Check Results
        run: |
          if [ ${{ steps.rust-lint.outcome }} == 'failure' ]; then
            exit 1
          fi
